format = """
[](fg:#88c0d0)[  $directory](bg:#88c0d0 fg:#2e3440)[](fg:#88c0d0 bg:#81a1c1)[ $git_branch$git_status ](bg:#81a1c1 fg:#2e3440)[](fg:#81a1c1)$character"""

[directory]
truncation_length = 3
style = "bg:#88c0d0 fg:#2e3440"

[git_branch]
symbol = " "
style = "bg:#81a1c1 fg:#2e3440"

[git_status]
style = "bg:#81a1c1 fg:#2e3440"

[character]
success_symbol = "[❯](bold #a3be8c)"
error_symbol = "[❯](bold #bf616a)"

[cmd_duration]
min_time = 2000
format = "took [$duration](#ebcb8b) "

[nodejs]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "
