[mgr]
marker_selected = { fg = "#a3be8c", bold = true }
marker_copied = { fg = "#ebcb8b", bold = true }
marker_cut = { fg = "#bf616a", bold = true }
border_style = { fg = "#88c0d0" }

[status]
perm_type = { fg = "#a3be8c" }
perm_read = { fg = "#ebcb8b" }
perm_write = { fg = "#bf616a" }
perm_exec = { fg = "#88c0d0", bold = true }

[input]
border = { fg = "#88c0d0" }
selected = { fg = "#2e3440", bg = "#88c0d0" }
